### ISSUE TITLE
Remove fragments and their usage from next.js example

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#102]
The fragment needs to be changed to css and the consumers need to use `composes`

https://github.com/zeit/next.js/blob/master/examples/with-emotion/pages/index.js#L34-L68

**Comment by hawkins** [comment]
I'd be happy to claim and tackle this one 😄 👍

**Comment by tkh44** [comment]
Please do @hawkins

**Comment by hawkins** [comment]
Opened a PR over on next for this (https://github.com/zeit/next.js/pull/2497)

**Comment by tkh44** [comment]
@hawkins Thanks! I approved the changes and that usually speeds things up

**Comment by hawkins** [comment]
Thanks - looks like it worked, it was just merged! 🎉

**Comment by hawkins** [comment]
Worth mentioning that I merged that PR into `v3-beta` instead of master since `v3-beta` is the default, although Next.js v3 is dropping very soon so it'll be merged to master before long.

**Comment by tkh44** [comment]
Thanks @hawkins !
