### ISSUE TITLE
CSS priority when composing multiple Styled Component

### ISSUE THREAD

**Issue by thangngoc89** [tkh44/emotion#104]
- `emotion` version:
- `react` version:

Relevant code.

```javascript
Component = styled.div``

ComponentDecorator = styled(Component)``
```

What you did:

Composing multiple styled component

What happened:

The css order is not guaranteed. 

Reproduction:

Problem description:

Suggested solution:

Concatenate css string instead of generating new class

**Comment by tkh44** [comment]
This might be related, we should detect if `tag.cls` exists and do something with that in `styled`.

**Comment by tkh44** [comment]
I put the difficult tag because of the fact that selectors get crazy with edge cases fast.

**Comment by thangngoc89** [comment]
How React Native solves this: 

![image](https://user-images.githubusercontent.com/3049054/27966043-fb44ad40-6367-11e7-8ad0-502336fe9f3d.png)

https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md#how-styles-are-resolved

**Comment by nishp1** [comment]
@tkh44 what are thoughts here? I think it makes sense to stick with and support browser behavior here.

**Comment by tkh44** [comment]
fixed in v7
