### ISSUE TITLE
Don't generate empty classes

### ISSUE THREAD

**Issue by thangngoc89** [tkh44/emotion#116]
- `emotion` version: 5.2.0
- `react` version: 15.x.x

Relevant code.

```javascript
const bold = css`font-weight: 700;`
const italic = css`font-style: italic;`
const secondColor = css`color: #7C7C7C;`

const f1 = css`font-size: .75em;`
const f2 = css`font-size: .875em;`
const f3 = css`font-size: 1em;`
const f4 = css`font-size: 2em;`

export const Word = styled("h1")`
  composes: ${bold} ${f4};
`
```

What you did:

- Use the above component

What happened:

- emotion generates empty class

![image](https://user-images.githubusercontent.com/3049054/27998762-403dc86e-653e-11e7-8573-1812d40e718f.png)

![image](https://user-images.githubusercontent.com/3049054/27998764-4ba2a800-653e-11e7-8571-1a726fc51964.png)

Reproduction:

Problem description:

As I understand, the redundant class were there for nesting selector. But I use that pattern a lot across the code base, I would hope the redundant class is removed when not neccessary

Suggested solution:

**Comment by tkh44** [comment]
I've noticed it too. Maybe @mitchellhamilton could shed some light on it.

**Comment by mitchellhamilton** [comment]
We could probably remove the rule but we need to keep the class on so it can be used as a selector.
