### ISSUE TITLE
Implement the plugin as a babel macro.

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#132]
We need this done in order to be ready for https://github.com/facebookincubator/create-react-app/issues/2730. For now, we could just do it alongside `babel.js` as `macro.js`. We can abstract most of `babel.js` easily (I think).

https://github.com/kentcdodds/babel-macros/blob/master/other/docs/author.md

https://github.com/kentcdodds/babel-macros/blob/master/src/__tests__/fixtures/emotion.macros.js

cc @kentcdodds @threepointone

**Comment by kentcdodds** [comment]
This is what I did for [preval](https://github.com/kentcdodds/babel-plugin-preval/compare/e2cc1a5d55fc9fe02e28518e7a388654267ff58f...600beb823d974e03b5d2d318ea6cc956d9e13ba4), if that helps at all :)
