### ISSUE TITLE
Consider moving to latest PostCSS for parsing

### ISSUE THREAD

**Issue by hzlmn** [tkh44/emotion#140]
Hello! 

While looking through source code i found that fact that you rely on legacy `postcss` and you  port it from `styled-components`. 

While it works fine, I was  wondering do you want to switch parser to latest `postcss@6.*`. It's leaner, use less memory and has some parsing updates. If so i can quickly submit a patch.

UPD Changelog for `6` version can be found [here](https://github.com/postcss/postcss/releases/tag/6.0.0)

**Comment by thangngoc89** [comment]
@hzlmn The reason why styled-components and emotion use legacy postcss is because it support synchronous API. Babel plugin must be sync , so you can't do anything async with it.

**Comment by hzlmn** [comment]
@thangngoc89 I strongly believe that you [can](https://github.com/postcss/postcss/blob/master/lib/lazy-result.es6#L129) use `sync` API if you need it.

**Comment by mitchellhamilton** [comment]
@hzlmn We've been planning to switch to actual PostCSS for a while and we would love a PR for it!

**Comment by tkh44** [comment]
This is in v7
