### ISSUE TITLE
Add documentation on the ability to conditionally add css declarations instead of just values

### ISSUE THREAD

**Issue by hamlim** [tkh44/emotion#148]
I was messing around with some ideas inside the Emotion site and realized you can do something like this: 
```javascript
const MyComp = styled.div`
  ${ prop => prop.value && `
    color: red;
    background-color: blue;
  `}
`;
```

### Suggestion:
It would be pretty neat to document this feature in my opinion, before this I was conditionally adding css via `classnames` and using `css`.
```Javascript
const classOne = css`
  color: red;
`
const classTwo = css`
  border-radius: 4px;
`
const classes = cx({
  [classOne]: props.isRed,
  [classTwo]: props.isRounded
})
```
 Not really sure where this could live within the documentation structure. Maybe like a high level API reference documenting `css`, `styled`, and conditional css via props?

Also this might be something to just add to the documentation issue currently open? If so I will copy some of the content and add it there and close this.

**Comment by mattfysh** [comment]
Can you nest callbacks e.g.
```javascript
${p => `color: ${p => p.t.red}`}
```

**Comment by mitchellhamilton** [comment]
We do not recommend doing this, we cannot autoprefix or do any other processing on things like this.

**Comment by tkh44** [comment]
@mitchellhamilton is right, but you can do this

```jsx
const MyComp = styled.div`
  composes: ${ prop => prop.value && css`
    color: red;
    background-color: blue;
  `}
`;
```

**Comment by mattfysh** [comment]
How about...

```javascript
const MyComp = styled.div`
  ${ prop => prop.value && `
    color: ${prop.theme.red};
    background-color: ${prop.theme.blue};
  `}
`;
```

Setting colors from theme values is a fairly common use case, I don't think it's a good idea to document (and, by extension, support) this approach if it doesn't support common use cases

**Comment by tkh44** [comment]
I'm not 100% sure this will work but it should...

```jsx
const MyComp = styled.div`
 composes: ${ prop => prop.value && css`
    color: ${prop.theme.red};
    background-color: ${prop.theme.blue};
  `}
`;
```

**Comment by hamlim** [comment]
The snippet above seems to only work if `MyComp` is nested within a theme provider, oddly didn't even work just by adding a prop directly on the component:
```Javascript
<MyComp theme={{blue: 'blue', red: 'red'}} />
```

Kind of feels odd to throw this kind of content all inside `composes`, maybe I just haven't wrapped my mind around that yet. IMO would be cool to have another api kind of like `css`

```Javascript
const MyComp = styled.div`
  ...
  ${ prop => prop.thing && insertStyles`
    color: red;
  `}
`;
```

That way you aren't limited to doing all this logic up on the first property and can split it up a bit. Just a thought. I will play around more with the composes and css solution and see if it starts to make more sense to me.

**Comment by mitchellhamilton** [comment]
I think a better way to split the logic up would be supporting multiple composes properties as long as they're the first rules which wouldn't be too hard. This would also match css modules.

**Comment by tkh44** [comment]
@hamlim ignore the props.theme part. That's just the example we had to work with. The point I was trying to get across is how powerful `composes` is. All of your examples work, just remember you need to wrap your style blocks with `css` in order to get prefixing/optimizations.

**Comment by hamlim** [comment]
Makes sense, thanks for the insight. I can close this issue out then. 👍
