### ISSUE TITLE
gitignore *.emotion.css files?

### ISSUE THREAD

**Issue by hemlok** [tkh44/emotion#161]
- `emotion` version: 5.2.0
- `react` version: 15.5.4

What you did:
I added *.emotion.css to my gitignore, pushed up, pulled down on other workstation.

What happened:
`Module not found: [CaseSensitivePathsPlugin] `.../src/App.emotion.css` does not match the corresponding path on disk - File does not exist.`

Reproduction:
Delete any *.emotion.css file when using in conjunction with an ejected create-react-app 1.3.0. Webpack Loaders:
```
      {
        test: /\.css$/,
        exclude: /\.emotion\.css$/,
        loader: 'style!css?importLoaders=1!postcss'
      },
      {
        test: /\.emotion\.css$/,
        loader: 'style!css?importLoaders=1!postcss'
      },
```

Suggested solution:
Is it possible to have emotion files generated on start if they are missing? It seems strange that they would be version controlled since they are generated. Am I missing something in my configuration? Or is this simply not an intended use case? 

Massive ❤️ for this project

**Comment by tkh44** [comment]
I've always just added them to the repo. I'm not sure we can do much about this issue. The imports are added automatically to the top of your js file.

**Comment by tkh44** [comment]
Why are you using 2 different loaders? Just use the same loader for both. Its valid css 😀

**Comment by hemlok** [comment]
Fair! I have no problem including them in the repo personally. It just strikes me that it would be nice if my colleagues didn't see the *.emotion.css in the git diff in our PRs, as well as get any ideas in their heads about editing the *.emotion.css 🤦‍♂️ I guess I'd just catalogue this as a *nice to have*. Thanks! 🎖

**Comment by hemlok** [comment]
AS for the loaders... ya I fixed that a bit back, leftovers from when I started this project and was fumbling around. Copying your emotion-rewired example in future 👌
