### ISSUE TITLE
Support for create-react-app?

### ISSUE THREAD

**Issue by MakiBM** [tkh44/emotion#166]
So I have a fresh app boostrapped with create react app. Added emotion to the project and trying to use it. Below is the error message I get. Any help on that one?

- `emotion` version: 6.0.3
- `react` version: 15.6.1

Relevant code.

```javascript
import React from 'react'
import styled from 'emotion/react'

const Header = styled.div`
  display: flex;
  width: 100%;
`
```

Error message
```
TypeError: __WEBPACK_IMPORTED_MODULE_1_emotion_react___default.a.div is not a function
Object../src/components/Header.js
src/components/Header.js:4
  1 | import React from 'react'
  2 | import styled from 'emotion/react'
  3 | 
> 4 | const HeaderClass = styled.div`
  5 |   display: flex;
  6 |   width: 100%;
  7 | `
```

**Comment by mitchellhamilton** [comment]
The most likely reason that you're getting that error is you don't have the babel plugin. Currently we recommend to use [`react-app-rewired`](https://github.com/timarney/react-app-rewired) if you're using `create-react-app`, you can look at an example of this [here](https://github.com/tkh44/emotion-create-react-app-example)

In the future [if `create-react-app` adds `babel-macros`](https://github.com/facebookincubator/create-react-app/issues/2730) it'll be as simple as importing `emotion/react/babel`.

**Comment by tkh44** [comment]
There is actually a preset for emotion here. https://github.com/osdevisnot/react-app-rewire-emotion

**Comment by MakiBM** [comment]
Thx guys for directions :)
