### ISSUE TITLE
emotion interacts poorly with babel-cli --out-dir

### ISSUE THREAD

**Issue by ChristopherBiscardi** [tkh44/emotion#167]
- `emotion` version: 6.0.3

Relevant code: https://github.com/ChristopherBiscardi/emotion-babel-bug

#### What you did:

Run `babel src --out-dir lib`

#### What happened:

`*.emotion.css` files are written in `src`, not in `lib`.

#### Reproduction:

```
git clone git@github.com:ChristopherBiscardi/emotion-babel-bug.git
cd emotion-babel-bug && yarn
yarn run build
```

#### Problem description:

[emotion/src/babel](https://github.com/tkh44/emotion/blob/02ab1b140542092d8bfd5b42c8745f1c59563d50/src/babel.js#L347-L366) writes this file out as a relative path.

 #### Suggested solution:

If babel allows access to an `--out-dir` configuration in the babel transformation, then use that to prefix the filename.

**Comment by mitchellhamilton** [comment]
It looks like this isn't possible.

https://github.com/babel/babel/blob/7.0/packages/babel-cli/src/babel/index.js#L204-L212

**Comment by ChristopherBiscardi** [comment]
I'm just `mv`ing the css files out on build right now. What do you think about adding an `outputDir` type option in the babel config for emotion?

**Comment by tkh44** [comment]
@ChristopherBiscardi can you open up a formal issue for that feature request please? I like that idea and I don't want it to get lost in the shuffle.

**Comment by ChristopherBiscardi** [comment]
@tkh44 formally added in #180

**Comment by tkh44** [comment]
Thank you @ChristopherBiscardi. I'm going to close this one.
