### ISSUE TITLE
Background url asset

### ISSUE THREAD

**Issue by HBCharles** [tkh44/emotion#172]
I'm moving all my css code to emotion. The background url doesn't find my assets in the public folder. Is there any configuration to make it working ?

**Comment by dkozickis** [comment]
@HBCharles did you figure it out?

**Comment by dkozickis** [comment]
Turns out it's a basic thing :) 

```javascript
import showPass from 'ic-show-pass.svg';
``` 

and then 

```javascript
 background: url(${props => (props.type === 'password') ? showPass : hidePass}) no-repeat;
```

or whatever you were doing

**Comment by Khrystyna** [comment]
What worked for me was: 

```
import icon from './icon.svg';
...
background: `url(${icon})`,
...
```
