### ISSUE TITLE
Unknown prop on DOM element

### ISSUE THREAD

**Issue by eXtreaL** [tkh44/emotion#183]
- `emotion` version: 6.0.3
- `react` version: 15.6.1

**Relevant code:**
```javascript
const Avatar = styled('img')`
  width: 96px;
  height: 96px;
  border-radius: ${props =>
    props.rounded ? '50%' : 0};
`
```
Example above is from https://emotion.sh/.

**What you did:**
Tried to render the example from above using 
```javascript
<Avatar rounded />
```

**What happened:**
I got the following error in my console: Unknown prop `rounded` on <img> tag. Remove this prop from the element.

**Problem description:**
I'm not sure whether this is a problem due to my configuration/implementation or if this is a problem in the library. I assumed this should work without any errors, since i copied the exact example from https://emotion.sh/. However when scanning emotion's source code i found that styled just blindly merges/spreads all the props onto the DOM element.

**Suggested solution:**
Whitelist the allowed props for each DOM element, which is the way styled-components is doing it at the moment.

**Comment by ai** [comment]
My temporary solution:

```js
const Avatar = styled('img')`
  width: 96px;
  height: 96px;
`

const RoundAvatar = styled(Avatar)`
  border-radius: 50%;
`

props.rounded ? <RoundAvatar> : <Avatar>
```

**Comment by divyagnan** [comment]
I don't know if this is a 'good' solution but I've been using the following and getting by without any errors:

```jsx
const e = React.createElement;

/* manually pull off the props that you will be using 
 * and then forward everything else to the createElement call
 */
const Button = styled(
  ({ backgroundColor, children, ...props }) => e("button", props, children)
)`
  background-color: ${props => props.backgroundColor};
`;

<Button backgroundColor="green">No Error!</Button>
```

**Comment by tkh44** [comment]
great stuff @divyagnan 

FWIW you can use recompose's `mapProps`

https://github.com/acdlite/recompose/blob/master/docs/API.md#mapprops

```
const omitProps = keys => mapProps(props => omit(keys, props))

styled(omitProps(Button))`
  color: blue;
`
```

**Comment by eXtreaL** [comment]
That's actually a pretty good solution, @divyagnan. However i would like to see this solved from the library instead. Currently i'm just directly using the css() function in my components instead of using styled(), passing the relevant props to css() and composing a style object (resulting in classnames) myself.

**Comment by tkh44** [comment]
@eXtreaL That is actually how I prefer to use emotion. You can also use the css prop on any element that supports `className`.

```
<div css=`color:blue;`/>
```

is compiled to

```
<div className={css`color:blue;`} />
```

**Comment by ai** [comment]
@tkh44 any plans to fix it in core?

**Comment by thangngoc89** [comment]
@ai from slack, styled will have anp new arg:

Styled("div", { omitProps: ["foo"] })

**Comment by ai** [comment]
@thangngoc89 you mean?

```js
const Link = styled.css`
  color: ${props => props.foo ? 'black' : 'red'};
`

<Styled foo={true} omitProps={['foo']}>
```

**Comment by thangngoc89** [comment]
@ai Sorry I was on my phone. It's like this 

```js
const Link = styled("div", { omitProps: ["foo"] })`...`

<Link foo="bar" />
```

**Comment by tkh44** [comment]
@ai I've been writing more and more emotion code and thinking on how I want to handle this in the core. Right now I'm using this setup.

```jsx
// base.js
import React from 'react'
import styled from 'emotion/react'
import { omit } from 'emotion/lib/utils'
import { space, width, fontSize, color } from 'styled-system'

import theme from './theme'

const defaultExcludedProps = [
  'm',
  'mt',
  'mr',
  'mb',
  'ml',
  'mx',
  'my',
  'p',
  'pt',
  'pr',
  'pb',
  'pl',
  'px',
  'py',
  'fontSize'
]

export default (tag, omitProps = []) => styled(props =>
  React.createElement(tag, omit(props, defaultExcludedProps.concat(omitProps)))
)`
  ${space};
  ${width};
  ${fontSize};
  ${color};
  color: ${theme.colors.gray[8]};
  font-family: 'Oxygen', sans-serif;
  box-sizing: border-box;
`
```

and usage

```jsx
import React from 'react'
import styled, { css } from 'emotion/react'
import base from '../base'
import theme from '../theme'

export default styled(base('input', ['omit', 'these', 'props']))`
  position: relative;
  display: block;
  width: 100%;
  border-radius: 0;
  background: ${theme.colors.gray[0]};
  font-weight: bold;
  -webkit-appearance: none;
  border: none;
  border-bottom: 1px solid ${theme.colors.green[5]};
  outline: none;
`
```

I've come to really like this pattern but I'm not sure how to make this a solution that works for everyone.

**Comment by souporserious** [comment]
I've been using glamor jsxstyle recently with some custom options that allow me to set global custom style props to strip out like `marginVertical`, `elevation`, etc.. similar to what you have above. Could it be a babel option? Or maybe you create your own `emotion`?  Super naive example:

```
import createEmotionFactory from 'emotion/create'
export default createEmotionFactory(['mv', 'mh', ...])

..later

import styled from './my-styled'
export default styled(base('input'))`
  position: relative;
  display: block;
  width: 100%;
`
```

**Comment by ai** [comment]
@tkh44 Wow, it was fast! I like Emotion community :).

Also, we may need docs for it since it is not clear.

**Comment by thangngoc89** [comment]
@ai you don't need to do anything on your side, just upgrade to the latest emotion beta.

**Comment by ai** [comment]
@thangngoc89 uh, so you clean all non-DOM props automatically? Awesome!

**Comment by thangngoc89** [comment]
Oh yeah. Thanks @mitchellhamilton for that

**Comment by tomduncalf** [comment]
Sounds like this should be fixed looking at the above, but with emotion 9.0.1 I still get an error e.g. with a `div`:

```
const Container = styled<{ backgroundColor: string }, 'div'>('div')(props => ({
  backgroundColor: props.backgroundColor,
}));
``` 

```
<Container backgroundColor={colors[0]}>
```

```
Warning: React does not recognize the `backgroundColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `backgroundcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Any advice? I am using this with `react-static` if that could make any difference...

**Comment by tkh44** [comment]
@tomduncalf I can't reproduce what you are describing here https://codesandbox.io/s/r552m5nvjo

**Comment by tomduncalf** [comment]
Interesting @tkh44, my next step was going to be a simple repro case. I guess something somewhere in my setup is breaking it. I'll look into it more when I have time :) Thanks!

**Comment by tomduncalf** [comment]
Sorry, I'd got a bit confused, don't write code late at night ;)

The issue is that the `react-router` `Link` component is passing through all the props it receives. I'm now manually instantiating it to filter the props, like:

```
const HomeItem = styled<IProps, 'Link'>((props: IProps) => (
  <Link to={props.to} className={props.className}>
    {props.children}
  </Link>
))((props: IProps) => ({
 ...
```

**Comment by bernharduw** [comment]
I also came across that issue, in my case with react-bootstrap's ListGroupItem, which also passes through all the props.

What do you think about an official `omitProps` option to styled?

```js
const ListItem = styled(ListGroupItem, { omitProps: ['color'] })`
  color: ${props => props.color || '#000'};
`;
```

My current workaround doesn't feel right nor readable:

``` js
const ListItem = styled(({ color, ...props }) => <ListGroupItem {...props} />)`
  color: ${props => props.color || '#000'};
`;
```

I could take a stab on a PR if you like that omitProps proposal.

**Comment by davej** [comment]
@bernharduw @mitchellhamilton: ^

Sorry for the rude ping. The post above has 6 thumbs up. Is it something that you would consider?

Finding this issue a lot with components in the Ant Design component library.

**Comment by Andarist** [comment]
This feature already is in emotion - check out shouldForwardProp

**Comment by davej** [comment]
Perfect thank you!
For anybody stumbling across this issue, take a look at #655.

**Comment by DylanVann** [comment]
With the new syntax I end up getting babel errors when compiling:

```jsx
styled(SomeComponent, { shouldForwardProps: func })`
```

I get: "Second argument to a styled call is not an object, it's going to be removed"

It doesn't emit an error when using a built in element, e.g.

```jsx
styled('a', { shouldForwardProps: func })
```

**Comment by Andarist** [comment]
That's weird. @DylanVann could u prepare a sample repo with the issue reproduced?

**Comment by bitttttten** [comment]
I am getting this error on a component:

```
Warning: React does not recognize the `isOpen` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isopen` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div
    in Box
    in StyledFlex (created by InteractiveMediaObject)
```

My component looks like:

```
import styled from 'react-emotion'
import { Flex, Box } from 'grid-styled/emotion'

const StyledFlex = styled(Flex)`
	background: ${({ variant, theme }) => theme.colours[variant || 'lightest']};
	position: relative;
	padding-left: ${({ isOpen }) => (isOpen ? '10rem' : 0)};
	transition: padding-left 0.2s ease;
`
```

and it's used like:

```
		return (
			<StyledFlex
				variant={variant}
				isOpen={this.isOpen}
				justifyContent="center"
				alignItems="center"
			>
				<ActionBox onClick={onAction}>{actionText}</ActionBox>
				<ImageBox
					image={image}
					onClick={this.toggle}
				/>
			</StyledFlex>
		)
```

I omitted a lot of code for beverity. Why is `isOpen` being passed down but none of the others?

**Comment by tgallacher** [comment]
I'm not familiar with `grid-styled/emotion`, but looking at the code I would guess that `variant`, `justifyContent` and `alignItems` are recognised props for their `Flex` API, and therefore they will take care of ensuring these don't propagate to the underlying DOM. 

However, `isOpen` is something I assume is what you have added and is thus not recognised by the `grid-styled/emotion` `Flex` component. Therefore, `styled` (from `react-emotion`) will pass everything through it doesn't recognise -- as it doesn't know if you are wrapping a base DOM node, or a custom component, and therefore can't know when or what to prevent propagating through. 

However, you can manually tell `styled` which props is should propagate and which it shouldn't, although the functionality doesn't seem to be well documented yet: See https://github.com/emotion-js/emotion/issues/655 for more info.

To fix the warning here, I think the following should do the job: 

```js
import styled from 'react-emotion'
import isPropValid from '@emotion/is-prop-valid'
import { Flex, Box } from 'grid-styled/emotion'

const StyledFlex = styled(Flex, { shouldForwardProp: isPropValid })`
	background: ${({ variant, theme }) => theme.colours[variant || 'lightest']};
	position: relative;
	padding-left: ${({ isOpen }) => (isOpen ? '10rem' : 0)};
	transition: padding-left 0.2s ease;
`
```

**Comment by bitttttten** [comment]
Is there an update on this yet? Couldn't `shouldForwardProp` be inherited from what is being passed into `styled(x)`?

It avoids making the below as verbose. It would be nice of StyledLink inherited shouldForwardProp from Link.

```
const StyledLink = styled(Link, {
	shouldForwardProp: isPropValid,
})<{ aspectRatio: number }>(({ theme, aspectRatio }) => ({
	display: `block`,
	position: `relative`,
	border: `1px solid ${theme.colours.primary}`,
	paddingBottom: `${100 / aspectRatio}%`,
}))
```

**Comment by SJATPS** [comment]
Is this issue fixed? if yes in which version?

**Comment by matheusslg** [comment]
Any update about this? The code below is just an example:

```js
const StyledInputField = styled('input', { shouldForwardProp: isPropValid })(({ leftElement }) => ({ 
  paddingRight: leftElement ? 40 : 0
}));
```

Since `leftElement` is not a valid prop, I cannot access this prop after `shouldForwardProp` validation, but if I remove it, I receive the `React does not recognize the leftElement prop on a DOM element.` warning.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by matheusslg** [comment]
There's another issue opened about the same problem, check it out, https://github.com/emotion-js/emotion/issues/2193

**Comment by Slapbox** [comment]
@Andarist do you know why it might be that Emotion doesn't produce identical warnings in CodeSandbox?

In the interest of providing a code sample, I tried to make one. This example produces the warning for us in our app, but transplanting it to CodeSandbox yields no warnings. The only difference that comes to mind is Babel plugins, but I don't see how they'd affect the warning.

https://codesandbox.io/s/emotion-issue-template-forked-5bmqmt?file=/src/App.tsx:0-115

Non-codesandbox-side it produces:
![image](https://user-images.githubusercontent.com/6835891/187794945-dcd5414c-22d0-4698-a28b-e5bd7d614c79.png)

**Comment by Andarist** [comment]
Emotion forwards it here but Framer Motion filters it out here:
https://github.com/framer/motion/blob/b5133f553afef699972b7838cad64763f0006989/packages/framer-motion/src/render/dom/use-render.ts#L20-L24

I can't say why it's forwarded within Framer Motion in your project - perhaps your `Component` there is not a string like `"div"`?

**Comment by fdev** [comment]
> Emotion forwards it here but Framer Motion filters it out

I'm using the following code to prevent inconsistent prop forwarding between Emotion and Framer Motion:

```jsx
import isValidProp from '@emotion/is-prop-valid'
import { MotionConfig } from 'framer-motion'

const App = ({ children }) => (
  <MotionConfig isValidProp={isValidProp}>
    {children}
  </MotionConfig>
)
```

**Comment by weiyanggod** [comment]
> 请始终尝试以可运行的形式共享重现案例 - 无论是通过提供要克隆的 git 存储库还是 codesandbox。即使给出了确切的步骤，OSS 维护者通常也没有时间设置重现。

This solves the warning!

**Comment by weiyanggod** [comment]
> 我发现一个简单的解决方法是只在用于样式的 props 前加上前缀`data-`。这将防止抛出错误。
> 
> 虽然这不是最理想的，但是它确实有效。

This solves the warning!
