### ISSUE TITLE
styling intermittent

### ISSUE THREAD

**Issue by geddski** [tkh44/emotion#187]
- `emotion` version: 6.0.3
- `react` version: same effect with both 16.0.0-beta.1 and 15.6.1

Relevant code.

```javascript
import { css } from "emotion";

const colorMe = css`
  color: blue;
  font-size: 50px;
`;

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className={colorMe}>Color Me</div>
      </div>
    );
  }
}
```

What you did:
I used `create-react-app` to make an app. Got emotion working with it via react-app-rewire and [react-app-rewire-emotion](https://github.com/osdevisnot/react-app-rewire-emotion).

Dropped in the above code into my component.

What happened:

It works on some compiles, randomly does nothing on other compiles.
![image](https://user-images.githubusercontent.com/515722/28648055-494eff26-7228-11e7-821e-259622481755.png)

no code change, just a new save/compile:
![image](https://user-images.githubusercontent.com/515722/28648059-57efed56-7228-11e7-834d-24a13e0ceb75.png)

Reproduction:
follow same steps with create-react-app. I also ruled out the rewire stuff by ejecting from create-react-app and hooking emotion up the regular way with the babel plugin.

Problem description:
Should work every time.

Suggested solution:
Maybe someone has seen this before and has an idea of what's going on?

**Comment by tkh44** [comment]
Thanks for the report. 

I think you are running extract mode. can you try running inline mode if that is the case.
```
return rewireEmotion(config, env, { inline: true });
```

You could also try installing the beta `yarn add emotion@beta`. It defaults to inline mode and fixes a ton of bugs.

**Comment by geddski** [comment]
Doesn't appear to happen in inline mode.

**Comment by tkh44** [comment]
This has been fixed in v7
