### ISSUE TITLE
[Suggestion] Support hybrid inline-extract mode ?

### ISSUE THREAD

**Issue by bogas04** [tkh44/emotion#194]
- `emotion` version: latest
- `react` version: latest

Problem Description:

Extract mode is great, however for browsers that don't support css-vars, keeping styles in JS for rules that don't have any dynamic part is a compromise. They don't require css-vars to be extracted out.

Suggested solution:

Proposal is to use a hybrid of extract and inline for the case where css-vars aren't supported. We shall extract the rules out in a file if they are idempotent (no dynamic part), and keep them inline otherwise. This will ensure even better performance for slower / older browsers by ensuring smaller JS bundle, even if they lack css-vars support.

**Comment by tkh44** [comment]
This is essentially how the version 7 beta works. Inline mode is the default and you can opt into having static styles extracted to files. There are no css vars.
