### ISSUE TITLE
Cannot import `ThemeProvider` from `emotion/react`

### ISSUE THREAD

**Issue by divyagnan** [tkh44/emotion#195]
Cannot import `ThemeProvider` from `emotion/react`

- `emotion` version: 6.0.3
- `react` version: 15.6.1

What you did:

Imported Theme 
```javascript
import { ThemeProvider } from 'emotion/react'
```

What happened:

I got the following error message:
```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
```
Image of the error message:
<details><summary>Screenshot of the error</summary>
<img width="1288" alt="screen shot 2017-07-27 at 3 34 57 pm" src="https://user-images.githubusercontent.com/4612594/28688813-31cc65dc-72e1-11e7-9fd1-c5f8cd2f20c8.png">
</details>

Reproduction:

Reproducible by importing `ThemeProvider` from `emotion/react`
```js
import { ThemeProvider } from `emotion/react`
```

Problem description:

It seems that `ThemeProvider` is not exported from the index here https://github.com/tkh44/emotion/blob/master/src/react/index.js. It is exported in this file though https://github.com/tkh44/emotion/blob/master/src/react/theming.js. 

So doing the following works (no error):
```js
import { ThemeProvider } from 'emotion/react/theming'
```
But the website shows (see below) importing from `emotion/react` not `emotion/react/theming`
<details><summary>Screenshot of the website</summary>
<img width="582" alt="screen shot 2017-07-27 at 3 39 46 pm" src="https://user-images.githubusercontent.com/4612594/28689047-28c26ecc-72e2-11e7-87ae-75ef3897497e.png">
</details>

Suggested solution:

Either export `ThemeProvider` from the index of the react folder or change the website/docs to reflect the correct import path (or clarify that users should use the external `theming` package to use theming).

**Comment by divyagnan** [comment]
Upon further review it looks like the docs already show the correct import path for `ThemeProvider` https://github.com/tkh44/emotion/blob/master/docs/theming.md. 

I guess all that is needed is for the website to be re-deployed.

**Comment by mitchellhamilton** [comment]
The website is now updated.

**Comment by dfguo** [comment]
It's changed to use theming package directly instead of a part of emotion code? https://github.com/tkh44/emotion/commit/502b76f6d651adbdb847d0bd12f6c583bfc692be 

Is this intentional @tkh44 ?

**Comment by thangngoc89** [comment]
@dfguo Yep. It's intentional.
