### ISSUE TITLE
Make jest-utils able to take in any `sheet` instance.

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#21]
If we can implement this feature, users of emotion will be able to use these utils as well.

```
expect.addSnapshotSerializer(serializer)
expect.extend(matcher)
```

```
expect.addSnapshotSerializer(serializer(sheet))
expect.extend(matcher)
```

This is the reason I had to fork https://github.com/kentcdodds/jest-glamor-react for the utils.

See my issue in that repo https://github.com/kentcdodds/jest-glamor-react/issues/5. I couldn't figure out how to do this without changing the api. We do not have that restriction in the repo so it can be accomplished in whatever way that works.

**Comment by mitchellhamilton** [comment]
I think this is actually possible without breaking the api.

https://github.com/mitchellhamilton/jest-glamor-react/commit/fe8bf2cd79e6ba62a404ec168b40f7ba55896ed7

I'll probably open a PR once I write tests.

**Comment by kentcdodds** [comment]
That's been merged and will be released in a minute. Enjoy!

**Comment by tkh44** [comment]
@kentcdodds thank you for keeping us updated.

**Comment by tkh44** [comment]
I will port the tests over after #23 is merged.
