### ISSUE TITLE
SSR + hyrdate causes two sets of <style> tags to be created

### ISSUE THREAD

**Issue by jonathaningram** [tkh44/emotion#216]
See example repo and follow the steps to install: https://github.com/zeit/next.js/tree/master/examples/with-emotion

- `emotion` version (same as that in the example repo, but also tried `6.0.3` and `7.0.4`)
- `react` version (`15.6.1` per the example repo)

What happened:

You can see below that there are two sets of `<style>` tags injected and it appears emotion is not respecting the IDs that were passed in with `hydrate`.

6.0.3:

![image](https://user-images.githubusercontent.com/626664/28800181-eaf58a6a-768e-11e7-8873-24acf1d2ce35.png)

7.0.4:

![image](https://user-images.githubusercontent.com/626664/28800259-40d211b0-768f-11e7-989c-f0601673f486.png)

I've also had this with my project using emotion but thought it would be easier to replicate by referring to the example repo.

**Comment by mitchellhamilton** [comment]
I've investigated this and I believe it's caused by `hydrate` being called late. You should be able to fix it by moving the `hydrate` call to a seperate file and importing it right at the top of the route.

If that fixes it, it would be amazing if you could submit a PR to next.js!

**Comment by jonathaningram** [comment]
@mitchellhamilton I will check this out after work today and let you know. If so, I'll provide some PRs.

**Comment by mitchellhamilton** [comment]
@tkh44 I've investigated this a bit more and we will need to add some stuff to handle `injectGlobal`, `keyframes` and `fontFace`.
