### ISSUE TITLE
float css not working even on applying cssFloat option

### ISSUE THREAD

**Issue by shivani137** [tkh44/emotion#222]
. Have temprorily put hack by
const SomeStyledComponent = styled.div((props)=> {
        return {
            float: "left",
            padding: "10px",
            width: "200px",
            fontSize: "11px"
        }
    });

- `emotion` version:
- `react` version:

Relevant code.

```javascript

```

What you did:
Created a styled component 
const SomeStyledComponent = styled.div(
        {
            float: "left",//tried cssFloat too
            padding: "10px",
            width: "200px",
            fontSize: "11px"
        }
    );

What happened:
On html it changes to css-float instead of just float
![image](https://user-images.githubusercontent.com/17876202/28871914-5f5645dc-77a4-11e7-81c5-42aaecc42850.png)

Reproduction:

Problem description: float is a reserved word in js so we need to use cssFloat. With CssFloat the css float property is not getting created

Suggested solution: Did not look into the code but would be happy to help if guided.

**Comment by tkh44** [comment]
That's weird! I'll take a look

**Comment by tkh44** [comment]
I took a quick look but I couldn't figure out when this key is changed. Any ideas @mitchellhamilton?

**Comment by mitchellhamilton** [comment]
It's done it `postcssJs.objectify`, the actual change is in [`camelcase-css`](https://github.com/stevenvachon/camelcase-css/blob/master/index.js#L16). I think we either need to change to our own objectifier or add a special case in the runtime.

**Comment by tkh44** [comment]
These are object styles though. They never go through the `objectify`.

**Comment by tkh44** [comment]
I think the short term fix is handling the special case in the core.

Long term fix would be trying to make postcss-js more customizable I think we should be able to provide our own `parser` & `objectify` to `postcss.sync/async`.

@ai Is this is something you would consider?

**Comment by mitchellhamilton** [comment]
I think a better short term fix would be changing it back to float in the babel plugin after prefixing/objectifying

**Comment by tkh44** [comment]
Ok I'll do that real quick

**Comment by ai** [comment]
@tkh44 it happens because old IE can’t parse `float` (same as `class`).

I don’t think that using `objectify` is a good idea for this case (it doesn’t generate CSS). It would be better to generate CSS from PostCSS AST.

**Comment by tkh44** [comment]
@ai we convert the strings to objects using PostCSS AST. By using objects internally we are able to do some really strong composition. The core of the runtime reduces the arrays and objects to insertRule calls (cached)

**Comment by ai** [comment]
Hm, maybe we can drop IE8 support and fix `cssFloat` after `camelcase-css` (or just fork library into the `postcss-js`). What do you think about it?

**Comment by tkh44** [comment]
It's all good it was just a one line change 😄

**Comment by tkh44** [comment]
This fix was released in `v7.0.7`
