### ISSUE TITLE
cascade order

### ISSUE THREAD

**Issue by TroutZen** [tkh44/emotion#226]
Problem description:
I need to pass a className to a component that exposes a className prop. Based on some parent components state I'd like an icon to be visible or not visible. I could render two different components, but then I lose my native css transition. 

```
const icon = css`
  opacity: 0;
  transition: opacity 0.1s ease-in-out;
`;

const iconVisible = css`
  opacity: 1;
`;
```

```
<Icon
  color={palette.primary}
  className={classNames({
    [icon]: true,
    [iconVisible]: !!this.state.value,
  })}
  onClick={this.onClear} />
```

Because of the way cascade order is determined, my opacity definition (opacity 1) is always overridden by the first definition.

![cascade_order](https://user-images.githubusercontent.com/8078841/28950606-3907fafc-787a-11e7-9c82-b2276477f3b5.png)

Does anyone have any ideas about how to best handle this type of situation?

**Comment by tkh44** [comment]
This assumes you are on version 7.
```
const transition = css`transition: opacity 0.1s ease-in-out;`

const icon = css`
  ${transition};
  opacity: 0;
`;

const iconVisible = css`
  ${transition};
  opacity: 1;
`;

**Comment by tkh44** [comment]
css can also be dynamic.

```jsx
const icon = css`
  opacity: ${!!this.state.value ? 1 : 0};
  transition: opacity 0.1s ease-in-out;
`;
```

**Comment by TroutZen** [comment]
Thanks @tkh44 
I dropped the css declaration into the component and used the second method you provided and its working nice - thx. Using the first suggestion I still get the same issue where both classes have the same specificity but the class that I am adding dynamically is declared earlier in the generated stylesheet. As a result the class that is declared later in the stylesheet overrides the first.
