### ISSUE TITLE
Add ChangeLog

### ISSUE THREAD

**Issue by ai** [tkh44/emotion#239]
The user which will find 7.0 release will not be able to quickly understand changes and how to migrate to new major release.

Other good reasons to have ChangeLog: http://keepachangelog.com

**Comment by Geczy** [comment]
Just saw the 7.0 release and have no idea what changed or what's deprecated. Please add one :)

**Comment by mitchellhamilton** [comment]
We need to add an actual changelog but lots of the changes are described [here](https://medium.com/@tkh44/emotion-7-7ef119c45869)

**Comment by Geczy** [comment]
Why was extract removed? Article doesn't say

**Comment by mitchellhamilton** [comment]
It wasn't fully removed, it was changed to only extract when there are no interpolations. This was done because it was very complex, couldn't be widely used since it required css vars and it had many specificity issues.

**Comment by Geczy** [comment]
There's a cost of performance to using inline, though

**Comment by silvenon** [comment]
[Changelog exists now](https://github.com/tkh44/emotion/blob/master/CHANGELOG.md), so this can be closed?
