### ISSUE TITLE
Dynamic CSS in Extract mode

### ISSUE THREAD

**Issue by ai** [tkh44/emotion#241]
I really like Extract mode, since static CSS is great for browser performance.

I understand that you remove dynamic extract mode, to support something like:

```js
styled`
  font-size: 20px;
  ${margins}
`
```

But maybe it is possible to extract `font-size: 20px` to CSS and use inline mode for dynamic part (`${margins}`)?

**Comment by tkh44** [comment]
You can use this method with css vars.

```jsx
/* eslint-disable react/prop-types */
import { css } from 'emotion'
import React from 'react'

class View extends React.Component {
  render() {
    const { className, ...other } = this.props
    return (
      <div
        {...other}
        style={{
          '--some-var': 'hotpink'
        }}
        className={viewClass}
      />
    )
  }
}

const viewClass = css`
  background: var(--some-var);
`

export default View
```

This is extremely performant.

**Comment by tkh44** [comment]
> But maybe it is possible to extract font-size: 20px to CSS and use inline mode for dynamic part (${margins})?

It will make no real difference performance wise to split them up. The insert call is made regardless.

**Comment by ai** [comment]
Yeap, it will work as temporary solution.

But not as long-term solution, because it requires more code and could not be everyday method. I choose Emotion especially because it provided this feature out-of-box.

**Comment by ai** [comment]
> It will make no real difference performance wise to split them up.

It will not give me a performance even if 90% of my components uses only static styles and I need dynamic styles only for few components?

**Comment by tkh44** [comment]
Extract static mode turns on a flag which extracts static styles as they are found. If it sees an expression it just skips that particular css call.

```jsx
// found css 
const staticCss = css`
  font-size: 20px;
  background: var(--some-var);
`
// zero expressions so extracted and replaced with
const staticCss = 'css-12345'
```

```jsx
// found css
const dynamicCss = css`
  font-size: 20px;
  background: ${bg};
`
// 1 expression found don't extract  and replaced with
const dynamicCss = css([], [bg], (x0) => ({ fontSize: 20, background: x0 }))
```



Does this make sense?

**Comment by ai** [comment]
Yeap, it will make sense. Does Emotion 7 sorry it right now? (I tried it and had no success)

**Comment by mitchellhamilton** [comment]
This should work on emotion 7 with the `extractStatic` option in the Babel plugin.

**Comment by ai** [comment]
@mitchellhamilton does it work with `styled` too?

**Comment by mitchellhamilton** [comment]
@ai yes.

**Comment by ai** [comment]
Strange. I will try to understand why it doesn’t work for me.

**Comment by tkh44** [comment]
are you using the `styled(MyComponent)` pattern anywhere?

**Comment by ai** [comment]
@tkh44 yeap, every link is `styled(Link)`

**Comment by tkh44** [comment]
What does link look like if you can share?

**Comment by ai** [comment]
```js
const Link = (props, { flux }) => {
  attrs.rel = props.target === 'blank' ? 'noopener' : null

  attrs.onClick = e => {
    if (props.target === '_blank' || e.button > 0 || e.which > 1 ||
        e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) {
      return
    }
    e.preventDefault()
    flux.getActions('page').open(props.href)
  }

  return React.createElement('a', attrs, props.children)
}
```

**Comment by tkh44** [comment]
Ok. I was just checking if it was a styled component. This is strange it should be working.

**Comment by ai** [comment]
Maybe it is my mistake. I will check it on the days.

**Comment by xiaofan2406** [comment]
I was having trouble understanding whats going in v7 as I don't have any `.emotion.css` files generated anymore.
Then I found out that if `css` contains any dynamic values, it will skip the whole `css` (I assume then the whole block is generated at run-time?). and only the 100% static `css` will be extracted into an css file.

I really like what @ai is proposing of having only the dynamic parts generated at runtime, and the static parts extracted.

Also, this may be off topic, but I thought extract mode in v6 is the most performant way as shown in benchmark results. Shouldn't it try to extract as much as possible so it is at the cost of build time, and having less things to do at runtime?

**Comment by ai** [comment]
@tkh44 I tested and seems like auto-dynamic mode doesn’t work in my case:

```json
{
  "plugins": [
    [
      "emotion/babel",
      {
        "extractStatic": true
      }
    ]
  ]
}
```

```js
const Content = styled.div`
  background; white;
  border: ${ p => p.isBlocked ? '10px solid red' : null }
`

export default ({ isBlocked }) => {
  <Content isBlocked={ isBlocked }/>
} 
```

It generates CSS class with `background; white`, but no `border'

**Comment by tkh44** [comment]
I made a branch with the example site using extract-static-mode.

https://github.com/tkh44/emotion/tree/extract-static-example

One thing I'd like to point out is the Preview component and how it is composing another styled component yet the styles are still extracted.

https://github.com/tkh44/emotion/blob/extract-static-example/example/src/preview/index.js#L12-L43

Take a look at that then look at what was extracted.

https://github.com/tkh44/emotion/blob/extract-static-example/example/src/preview/index.emotion.css#L1-L31

**Comment by ai** [comment]
@tkh44 but they didn’t contain dynamic properties with `${}`. My code is:

```js
const Content = styled.div`
  background; white;
  border: ${ p => p.isBlocked ? '10px solid red' : null }
`
```

**Comment by tkh44** [comment]
```
const Content = styled.div`
  background; white;
  border: ${ p => p.isBlocked ? '10px solid red' : null }
`

**Comment by ai** [comment]
@tkh44 nope, this typo I made when copy tests. I can send PR with test case to your project.

**Comment by ai** [comment]
I made a test case, but everything is working on your website. Maybe I did it wrong on my site. I will close this issue, until some better investigation.

Thanks for the help.
