### ISSUE TITLE
composing css fragment with dynamic props

### ISSUE THREAD

**Issue by dfguo** [tkh44/emotion#244]
When composing a css fragment that uses props, the props won't be used.

- `emotion` version: 7.0.11
- `react` version: 15.6.1

Relevant code.

```javascript

const color = css`
  color: ${props => props.color};
`

const padding = css`
  padding: ${props => props.padding}px;
`

const Container = styled.div`
  composes: ${color} ${padding};
`

```

What you did:

I was hoping that we can dynamically composes and give dynamic css behavior to a component.

What happened:

raw string value of the function appears in the css value

Maybe there is a better way to do it? Let me know.

**Comment by mitchellhamilton** [comment]
If you want to do this, wrap css in a function that accepts props and interpolate the function.

**Comment by dfguo** [comment]
const color = (props) => css`
  color: ${props.color};
`

const padding = (props) => css`
  padding: ${props.padding}px;
`

const Container = styled.div`
  composes: ${props => {
    return ${color(props)} ${padding(props)};
  }};
`

works. Thanks @mitchellhamilton

**Comment by mitchellhamilton** [comment]
Just so you know, you don't need the extra function in the composes interpolation, you can just interpolate color and padding.

**Comment by tkh44** [comment]
You can do this as well @dfguo.
```
const color = (props) => css`
  color: ${props.color};
`

const padding = (props) => css`
  padding: ${props.padding}px;
`

const Container = styled.div`
  ${color};
  ${padding};
`
```

**Comment by dfguo** [comment]
@mitchellhamilton I'm not sure If I follow. Do you mind showing it with code snippet? Thanks!

**Comment by mitchellhamilton** [comment]
```jsx
const color = (props) => css`
  color: ${props.color};
`

const padding = (props) => css`
  padding: ${props.padding}px;
`

const Container = styled.div`
  composes: ${color} ${padding};
`
```

**Comment by aamir-mns** [comment]
I have breakpoints defined in my theme and was hoping to expose a simple function like this
```js
export const mq = (breakPoint: BreakPoints) =>
  css`
    @media (min-width: ${({ theme }) => theme.grid.breakPoints[breakPoint]}px);
  `;
```

so I can use it like this for example:
```js
const BasketCount = styled.span`
  top: 8px;
  ${mq('md')} {
    top: 9px;
  }
`;
```

does this mean that I have to do something like this?:
```js
const BasketCount = styled.span`
  top: 8px;
  ${({theme}) => mq(theme, 'md')} {
    top: 9px;
  }
`;
```

this is what I have in my theme file
```
breakPoints: {
      md: 768,
      lg: 992,
},
```

**Comment by aamir-mns** [comment]
> I have breakpoints defined in my theme and was hoping to expose a simple function like this
> .....

Update:
Got it. I think I just need a curry function like this:

```ts
const mq = (breakPoint: BreakPoints) => => ({theme}: {theme: Theme})
  css`
    @media (min-width: ${theme.grid.breakPoints[breakPoint]}px);
`;
```

**Comment by aamir-mns** [comment]
It does work for using like this
```js
const Grid = styled.div`
  border: 5px solid pink;
  ${mq('md')} {
    border: 5px solid red;
  }
`;
```

but not

```js
export const Grid = styled.div`
  ${() => {
    return `
      border: 5px solid pink;
      ${mq('md')} {
        border: 5px solid red;
      }
    `;
  }}
`;

any suggestions?
@mitchellhamilton / @tkh44 ?
```

**Comment by srmagura** [comment]
@aamir-mns I don't think we support this:

```jsx
export const Grid = styled.div`
  ${({ someProp }) => {
    // return some CSS based on someProp
    return `
      border: 5px solid pink;
      ${mq('md')} {
        border: 5px solid red;
      }
    `;
  }}
`
```

You could either manually pass the `theme` to your `mq` function or use statically-defined breakpoints.

**Comment by aamir-mns** [comment]
@srmagura it makes sense. I end up passing theme. Thanks
