### ISSUE TITLE
Conditional blocks of rules emits console.warn 

### ISSUE THREAD

**Issue by ericclemmons** [tkh44/emotion#246]
- `emotion` version: ^7.0.12
- `react` version: 15.4.1

Relevant code.

```javascript
export default withTheme(styled.label`
  label& {
    ${(props) => props.disabled ? css`
      cursor: not-allowed;
      opacity: 0.6;
    ` : ""}
  }
`);
```

What you did:

> Rendered the component.

What happened:

> Warning: Unsupported style property css-1kw3xf9. Did you mean css1kw3xf9?

Reproduction:

> N/A

Problem description:

> The line of code that conditionally inserts a block of rules is the culprit. 

Suggested solution:

> Is this something that can be supported, or is the recommendation to move all conditional logic to each individual key/value pair?

**Comment by ericclemmons** [comment]
Confirmed that this does not emit a warning:

```js
cursor: ${(props) => props.disabled ? "not-allowed" : "inherit" };
opacity: ${(props) => props.disabled ? 0.6 : "inherit" };
```

**Comment by ericclemmons** [comment]
With just `emotion`:
- quick-degree-finder-index-js.js.gz    21.5 kB
- polyfills.js.gz    29.3 kB

**Comment by ericclemmons** [comment]
If we drop `preact-compat`:

- quick-degree-finder-index-js.js.gz    18.4 kB
- polyfills.js.gz    29.3 kB

**Comment by tkh44** [comment]
The simple fix is to wrap your "else" in css.

```
export default withTheme(styled.label`
  label& {
    ${(props) => props.disabled ? css`
      cursor: not-allowed;
      opacity: 0.6;
    ` : css``}
  }
`);
```

The better fix is something like this.
```
const Label = styled.label`
  label & {
    ${(props) => props.disabled && css`
      cursor: not-allowed;
      opacity: 0.6;
    `}
  }
`
```

![image](https://user-images.githubusercontent.com/662750/29141083-ff53745a-7d09-11e7-8e87-4dddd52023ba.png)

We should have better errors to suggest this though.

**Comment by tkh44** [comment]
If you look at the compiled code it may make it more clear why this works.

```jsx
var Label = /* #__PURE__ */ styled(
  'label',
  'css-17fi7rq0',
  [],
  [
    function (props) {
      return (
        props.disabled &&
        /* #__PURE__ */
        css([], [], function createEmotionStyledRules () {
          return [
            {
              cursor: 'not-allowed',
              opacity: '0.6'
            }
          ]
        })
      )
    }
  ],
  function createEmotionStyledRules (x0) {
    return {
      '& span': {
        $0: x0
      }
    }
  }
)
```

**Comment by ericclemmons** [comment]
Ah, thanks for this!  We're converting from `styled-components` and I guess we found that false-y values were removed implicitly.
