### ISSUE TITLE
react-test-renderer render fails in Jest when using emotion's styled

### ISSUE THREAD

**Issue by darrentorpey** [tkh44/emotion#251]
- `emotion` version: 7.0.12
- `react` version: 15.6.1

**Relevant code / What you did:**

I set up this minimal repo to demonstrate the issue (README text included here as well)
https://github.com/darrentorpey/emotion_jest_react_test_renderer_issue

**What happened & repro:**

If you export `AvatarStyled` instead of `AvatarCSS` the Jest test fails with an error message:

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

This is currently blocking me from using `styled` altogether, which is a huge bummer.

**Comment by mitchellhamilton** [comment]
You don't have emotion's babel plugin in your `.babelrc`

**Comment by darrentorpey** [comment]
Ah, that was it, @mitchellhamilton -- thanks!

I initially set up emotion based on the introductory article, which does not mention that plugin at all.
