### ISSUE TITLE
injectGlobal and friends should support dynamic expressions.

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#254]
- `emotion` version:
- `react` version:

Relevant code.

```javascript
const test = css`
  background: aquamarine;
`

injectGlobal`  
  body > div:first-of-type, 
  #app, 
  #__next, 
  #__next > div {
    display: flex;
    flex: 1;
    height: 100%;
    ${test};
  }
`

```

What you did:

What happened:

All styles in the block do not work.

Suggested solution:
Specified elements should have an aquamarine background.

**Comment by heaversm** [comment]
Just a note - my styles were actually applied by using this format, but I still got warning errors for injected styles in the console (even if just one was dynamic:

```
injectGlobal`
  :root {
    --colors_blue_dark: ${__UT__ ? '#324980' : '#3b5998'};
    ...
  }
`
```

![screen shot 2017-08-11 at 2 10 22 pm](https://user-images.githubusercontent.com/520541/29232201-3b30f204-7e9f-11e7-860e-951694f0232e.png)
<img width="331" alt="screen shot 2017-08-11 at 2 10 32 pm" src="https://user-images.githubusercontent.com/520541/29232202-3b312544-7e9f-11e7-8765-78b5342f9724.png">

**Comment by tkh44** [comment]
Interesting use case @heaversm. That looks like a bug.
