### ISSUE TITLE
What is the Recommended Method to Test?

### ISSUE THREAD

**Issue by mgreystone** [tkh44/emotion#263]
- `emotion` version: 6.0.3
- `react` version: 15.4.2

What is the recommended way to test rendered styles?

The best i've been able to do on my on is test the value of the resulting `classNames` attribute. For example, a Jest snapshot might look like this:

```
<main
  className="css-Main-f15826-152jt63 css-Main-f15826 css-sansSerif-1a1xnm6-voi0on css-sansSerif-1a1xnm6 css-fontSizeRegular-aw3xrg-5sbaks css-fontSizeRegular-aw3xrg"
>
```

Is there any way to test the style rules themselves? I've seen projects like [jest-glamor-react](https://github.com/tkh44/jest-glamor-react), but that does not seem to have any effect on my end.

Thanks.

**Comment by thangngoc89** [comment]
You need to configure jest glamor react to use emotion stylesheet.

![img_2723](https://user-images.githubusercontent.com/3049054/29332634-e833deb0-822a-11e7-8b3d-814bbedf6877.PNG)

**Comment by mgreystone** [comment]
@thangngoc89 That's the step i was missing. Thank you!

Answered, closing.
