### ISSUE TITLE
[Help Wanted] Emotion erratic behavior

### ISSUE THREAD

**Issue by ap-o** [tkh44/emotion#277]
Hi, i'm just trying to use emotion on a side project of mine, and i'm getting some behavior that i can't understand or figure out where its coming from.

I got two example repositories

https://github.com/ap-o/tarmac-emotion
In this one, I got a very basic quick example and it all seems to be working just fine. Absolutely no problems.

https://github.com/ap-o/intro
But in a slightly more complex environment, its behaving really really weird.

Both those project have almost identical core dependencies, node 8, react 15, babel 6, webpack 3.

```
import React from 'react';
import styled from 'emotion/react';

const Container = styled('section')`
  display: flex;
  flex-direction: column;
  background-color: #e0e0e0;
  min-height: 100vh;
  flex: 1 0 100%;
`;

const HeaderOne = styled('h1')`
  font-size: 3.4rem;
  line-height: 1em;
  margin: 0 0 0.67em 0;
`;

const Login = () => {
  return (
    <Container>
      <HeaderOne>Login</HeaderOne>
      <a href="http://localhost:3000/auth/google">Login with google</a>
    </Container>
  );
};

export default Login;
```

Rarely, but sometimes it works as expected. I can modify the styles and the modules are hot reloaded properly. Then i might refresh the page, or just change something absolutely insignificant such as a tiny piece of markup: 
```
<HeaderOne>Login</HeaderOne>
to
<HeaderOne>Login yeah</HeaderOne>
```
And its broken...

```
Uncaught TypeError: (0 , _react4.default) is not a function
    at eval (index.js:17)
    at Object../src/browser/components/layout_login/index.js (intro.js:2849)
    at __webpack_require__ (vendors.js:704)
    at fn (vendors.js:117)
    at eval (login.js:11)
    at Object../src/browser/routes/login.js (intro.js:2977)
    at __webpack_require__ (vendors.js:704)
    at fn (vendors.js:117)
    at Object.eval (index.js:39)
    at eval (index.js:175)
```

The only idea i have is perhaps a babel plugin is conflicting, but i replicated everything except `react-hmr` and didn't resolve the issue.

**Comment by mitchellhamilton** [comment]
Could you show the full stack trace?

**Comment by ap-o** [comment]
@mitchellhamilton updated the post to include the full error.

**Comment by mitchellhamilton** [comment]
What version of emotion are you on? Also would you be able to push the changes that are causing the problem to that repo, maybe on a different branch.

**Comment by ap-o** [comment]
Both are using emotion 7.2.0. 

Here's the branch with emotion. Sorry about that, had pushed to the wrong origin.
https://github.com/ap-o/intro/tree/emotion

It seems like i found what's causing the problem. 

I am using the webpack CommonsChunkPlugin for a vendors chunk, which included all things react, but not emotion. As soon as i added emotion to the vendors entry config, it all worked fine.

**Comment by mitchellhamilton** [comment]
Great! Closing since it's solved.
