### ISSUE TITLE
Extract css

### ISSUE THREAD

**Issue by ai** [tkh44/emotion#282]
I found that `css` styles are not extracted, so my PostCSS plugins don't apply.

```js
const body = css`
  clear: fix;
`
```

It is by design, or I did something wrong?

**Comment by mitchellhamilton** [comment]
That's strange, `css` styles should be extracted(assuming they don't have any interpolations), I just tested it with an ejected CRA and it worked.

**Comment by ai** [comment]
Oops.  Maybe my fail again (should test better before creating issue 😅).

I will send more details tomorrow.

**Comment by ai** [comment]
Yeap, it was my fault. Sorry for attention. You did a great work and support works perfectly.

**Comment by ai** [comment]
I will try to investigate more deeper before open a issue next time :sweat:
