### ISSUE TITLE
Add benchmarks: glamorous and styled-components

### ISSUE THREAD

**Issue by neoziro** [tkh44/emotion#38]
Your solution seems to offer better performances than glamorous and styled-components. You should make it appear in the documentation.

Even without benchmarks, you should explain differences between other solutions like styled-components. They look pretty similar and that was my first question when I discovered your project.

**Comment by tkh44** [comment]
Great idea. If someone wants to add emotion to https://github.com/A-gambit/CSS-IN-JS-Benchmarks that should be a good start.

**Comment by chirag04** [comment]
a compares of emotion with glamorous and  styled-components would help a lot.

**Comment by tkh44** [comment]
@chirag04 
https://github.com/tkh44/emotion/blob/master/docs/benchmarks.md

**Comment by chirag04** [comment]
@tkh44 this is great and very helpful. by comparison i meant in terms of the api and how emotion solves the problem better and differently. mostly y emotion over glamorous or styled-component.

PS: I'm new to the css-in-js world and trying to understand the solutions better.

**Comment by tkh44** [comment]
@chirag04 I understand. Once the API settles down a bit more we will be able to document it fully and communicate the differences in a complete manner.

**Comment by tkh44** [comment]
I'm going to close this issue and open a new one for the compare and contrast.

**Comment by neoziro** [comment]
Nice!
