### ISSUE TITLE
injectGlobal throws an error

### ISSUE THREAD

**Issue by mitchellhamilton** [tkh44/emotion#45]
- `emotion` version: 4.1.2
- `react` version: 15.5.4

Relevant code.

```jsx
injectGlobal`any css`
```

What you did:

Run that through the babel plugin and the babel presets in the example(`env`, `react` and `stage-2`) and run it.

What happened:

![screen shot 2017-06-29 at 7 37 31 am](https://user-images.githubusercontent.com/11481355/27661643-6567e8c0-5c9e-11e7-8eeb-8fdc92769ac8.png)

Suggested solution:

I'm working on it, I think the `if` for `injectGlobal` in the babel plugin isn't working so babel transforms the tagged template literal so when it's run `injectGlobal` tries to call `undefined` as if it is a function. This could be wrong since the tests look fine, it might have something to do with other babel plugins running before this.

I think this only occurs in extract mode.

**Comment by tkh44** [comment]
Turn off the babel transform for tagged-template-literals and see if that fixes it. If it does we need to "lift" the visitor up I guess.

**Comment by mitchellhamilton** [comment]
I think the issue is related to static extraction

**Comment by mitchellhamilton** [comment]
Nevermind. This was the actual code, it wasn't the babel plugin's fault.


```jsx
injectGlobal(`
  html, body {
    font-family: -apple-system,
      BlinkMacSystemFont,
      "Segoe UI",
      "Roboto",
      "Roboto Light",
      "Oxygen",
      "Ubuntu",
      "Cantarell",
      "Fira Sans",
      "Droid Sans",
      "Helvetica Neue",
      sans-serif,
      "Apple Color Emoji",
      "Segoe UI Emoji",
      "Segoe UI Symbol";
    color: #495057;
    width: 100%;
    height: 100%;
    padding: 0;
    margin: 0;
  }
`)
```
