### ISSUE TITLE
Support Vue

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#46]
Is this even a thing in Vue?

```javascript
import Vue from 'vue'
import { css } from './index'

export default function (tag, cls, vars = [], content) {
  return Vue.component('styled', {
    props: ['class'],
    template: `<${tag} v-bind:class="[{{class}}, ${css(
      cls,
      vars.map(v => (v && typeof v === 'function' ? v(props) : v)),
      content
    )}]"><slot></slot></p>`
  })
}
```

Suggested solution:
Learn Vue

**Comment by mitchellhamilton** [comment]
I think Vue converts templates into jsx.

**Comment by mitchellhamilton** [comment]
https://github.com/styled-components/vue-styled-components/blob/master/src/models/StyledComponent.js#L11-L40

**Comment by lukeed** [comment]
Haven't tried locally, but how about something like this:

```js
import { css } from './index'

Vue.component('styled', {
  props: ['class'],
  render(h) {
    const ourCss = css(
      cls,
      vars.map(v => (v && typeof v === 'function' ? v(props) : v)),
      content
    );

    const attrs = { class: `${this.class} ${ourCss}` };

    return h(tag, { attrs }, this.$slots.default);
  }
});
```

> Mostly from [docs example](https://vuejs.org/v2/guide/render-function.html#Complete-Example)

**Comment by mitchellhamilton** [comment]
I've tested this locally and it works except for the name so you can only have one component. I'm trying to extract the name from the class name but it's being strange.

```js
import Vue from 'vue'
import { css as magic } from 'emotion'

const styled = (tag, cls, vars = [], content) => {
  Vue.component('styled', {
    functional: true,
    render (h, context) {
      const className = magic(
        cls,
        vars.map(v => (v && typeof v === 'function' ? v(context.props) : v)),
        content
      )
      return h(tag, { class: context.props.class
          ? className + ' ' + context.props.class
          : className })
    }
  })
}

export default styled

**Comment by tkh44** [comment]
@mitchellhamilton I think class can be an array so you can lose the concat. Not 100% sure if it works with `h` though.

**Comment by egoist** [comment]
You don't need to register the component globally I guess? I mean no need of `Vue.component('styled', component)`, just return the `component` object.

**Comment by mitchellhamilton** [comment]
Thanks @egoist, it's working perfectly now, about to submit a PR.
