### ISSUE TITLE
Drop the function call if the css was extracted and there were no dynamic values.

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#49]
We can avoid most function calls by just assigning the string. On large code bases this could be significant to startup time.

```jsx
const myClassName = css("css-cu78iu", []);
```

Should be

const myClassName = "css-cu78iu";

Suggested solution:

Here: https://github.com/tkh44/emotion/blob/8fb17180f2d1cfc966ed05a59efe04bb0ece12be/src/babel.js#L142-L157

```jsx
if (isStatic) {
  state.insertStaticRules(rules)
  return t.stringLiteral(`${name}-${hash}`)
} else {
  // ...
}
return t.callExpression(identifier, args)
```

**Comment by mitchellhamilton** [comment]
It's actually slightly more complex than that. `isStatic` means different things in different places. There it means it doesn't have any `@apply`s
