### ISSUE TITLE
Support identifiers for css prop

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#55]
Just as a start this enables fragments to be used as the value. This will enable some cool composition.

I want the css prop to accept arrays and other types as well I think. I think we can add some of the glamor api mechanics here and really get something going.

**Comment by braposo** [comment]
I just read your medium post and came here to search for array support after I realised it didn't work on your demo page 😆 

Just wanted to add a common use-case for me when using `glamorous` that I wish was also supported in `emotion` so we could consider changing in the future.

```js
export const Section = glamorous.div(({ noPadding, withDivider }) => [
    {
        paddingTop: $scale[8],
        paddingBottom: $scale[8],
        position: "relative",

        [`@media ${breakpoints.mdMax}`]: {
            paddingTop: $scale[7],
            paddingBottom: $scale[7],
        },
    },
    noPadding && {
        paddingTop: 0,
        paddingBottom: 0,
        [`@media ${breakpoints.mdMax}`]: {
            paddingTop: 0,
            paddingBottom: 0,
        },
    },
    withDivider && {
        paddingBottom: 0,
        [`@media ${breakpoints.mdMax}`]: {
            paddingBottom: 0,
        },
    },
]);
```
