### ISSUE TITLE
Tool to convert css modules to emotion

### ISSUE THREAD

**Issue by mitchellhamilton** [tkh44/emotion#70]
Something like a jscodeshift (we might not be able to use jscodeshift since it'll have to look at css files) code mod would be amazing to automatically convert css modules to emotion.

https://github.com/css-modules/postcss-icss

**Comment by choffmeister** [comment]
Not sure if this is still interesting for someone, but for those that stumble upon this page: I wrote a tool that will help me to do this task at least for 80%: https://github.com/choffmeister/cssmodules-to-emotion

So will still need some manual work afterwards, but should already help a lot.

**Comment by threepointone** [comment]
I’ve been thinking about this lately, and I think codemodding to js isn’t the solution. Rather, a css loader that converts to js would be much nicer for people already using that stack. They could even continue using css modules and whatever tools and workflows they’re used to, and still benefit from all the emotion fun stuff
