### ISSUE TITLE
Allow composing of styled components.

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#74]
```jsx
const BaseText = css`
 font-family: sans-serif;
`

const H1 = styled.h1`
  font-size: 48px;
`

const Title = styled.div` // <-- just ignore tag? or should we literally compose for the user?
  color: green;
`

const Heading = styled.div`
  composes: ${BaseText} ${H1} ${Title};
  text-align: center;
`
```

If we composed for the user the result would look like:

```html
<div class="css-1">
    <h1 class="css-2">
        <div class="css-3 BaseText-1">
              Children here and we just pass through all props
        </div>
    </h1>
</div>
```

**Comment by browniefed** [comment]
Is the intention to compose the components or compose the styles?

**Comment by tkh44** [comment]
You know I'm asking myself the same thing. What I'm doing here is basically slinging mud against the wall and seeing what sticks 😅

I originally wanted to compose just the styles and then I was thinking about all the times I'm writing out a layout and I do this pattern by hand. 

This would probably be a better idea for composing components.

```jsx
const Heading = styled([H1, Title])`
  font-size: 20px;
  
  ${Title} {
    font-family: serif;
  }
`
```
outputs

```html
<h1 class="css-1">
        <div class="css-Title-3">
              Children here and we just pass through all props
        </div>
</h1>
```

**Comment by browniefed** [comment]
Ha yeah I get it. 
Hmm what is the benefit of this syntax vs just using `children` as normal? Also why the  additional syntax here? Seems to over complicate things when combining styles would have the same effect technically.

I'm just wondering if this style makes too many assumptions about `layout vs style` that should be solved in the user world?

**Comment by tkh44** [comment]
Yes we are. On to the next idea... 😄

**Comment by browniefed** [comment]
I've killed an idea! Oh no! I'm so sorry.
