### ISSUE TITLE
Document keyframes

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#78]
https://github.com/tkh44/emotion/blob/master/docs/keyframes.md

Suggested solution:
Explain the basics of keyframes.

**Comment by natenorberg** [comment]
Do you mean explaining that the `keyframes` function takes in keyframes and returns an animation name like the `css` function returns a class name?

Or does this to give an introduction to keyframes in general?

**Comment by tkh44** [comment]
@natenorberg both would be awesome. I would settle for just a basic explanation at this point 😅
