### ISSUE TITLE
Server Side Rendering example with NextJS out of date.

### ISSUE THREAD

**Issue by hamlim** [tkh44/emotion#80]
The NextJS SSR example link has some out of date code (See NextJS link found here): https://github.com/tkh44/emotion#server-side-rendering

- `emotion` version: `^5.0.0`
- `react` version: `16.0.0.alpha.13`

Relevant code.

```javascript
// Current out of date code inside pages/_document.js
import { renderStaticOptimized } from 'emotion/server'

export default class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const page = renderPage()
    const styles = renderStaticOptimized(() => page.html)
    return { ...page, ...styles }
  }
  ...
}
```

What happened: `renderStaticOptimized` is not a function (was renamed just 2 days ago)

Suggested solution:

Update the example above to:
```javascript
import { extractCritical } from 'emotion/server' // change here

export default class MyDocument extends Document {
  static getInitialProps ({ renderPage }) {
    const page = renderPage()
    const styles = extractCritical(() => page.html) // change here
    return { ...page, ...styles }
  }
  ...
}
```

If this looks alright I can open a PR in NextJS to update this example.

**Comment by mitchellhamilton** [comment]
We also changed the api slightly so it's
```jsx
extractCritical(page.html)
```
but other than that it looks good(you will also need to update the `emotion/styled` import to `emotion/react`). Definitely submit a PR!

**Comment by tkh44** [comment]
Great work @hamlim Thanks for doing this for us.
