### ISSUE TITLE
Dynamic composes values based on props

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#90]
I want to support choosing what to compose with based on props.

```javascript
const Alert = styled('div')`
  composes: ${props => types[props.type]};
  padding: 10px;
`
```

**Comment by souporserious** [comment]
Any possibility of allowing pseudo selectors with dynamic composes?

**Comment by tkh44** [comment]
@souporserious can you give a small example of what you are wanting?

**Comment by souporserious** [comment]
Yes, sorry, I tried out [my block](https://github.com/tkh44/emotion/issues/73#issuecomment-312509165) from the last issue and the hover styles didn't seem to get applied 😕

**Comment by mitchellhamilton** [comment]
@souporserious It looks like you wrote the selector incorrectly. You wrote `&:hover:`. If you remove the extra colon it works fine.

**Comment by souporserious** [comment]
💩 sooooo sorry!!! Thank you so much @mitchellhamilton 🙏 for everything ❤️
