### ISSUE TITLE
How to handle condition declarations / Handling null values

### ISSUE THREAD

**Issue by hamlim** [tkh44/emotion#96]
- `emotion` version: `^5.1.1`
- `react` version: `^15.6.1`

### Relevant code.

```javascript
import {css} from 'emotion';

const styleDefaults = brand => ({
  background: brand === 'a' ? 'blue' : null
});

const MyComponent = ({brand, ...others}) => {
  const divClass = css`
    background: ${styleDefaults(brand).background};
  `;
  return <div className={divClass}>Content</div>;
}

<MyComponent brand="b" />
```

### What you did:
A fairly common use case I will need is to support different css for different brands using the same shared components. If the value for a particular css declaration is null for a brand, ideally that declaration should be stripped/omitted from the generated css. I am using Emotion in `inline` mode.

### Generated css:
```CSS
.css-divClass-[hash] {
  background: null;
}
```

### Suggested solution:
If the computed value is null, don't add the css declaration. Or communicate a better alternative to add conditional declarations.

**Comment by tkh44** [comment]
I tend to use the [`initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/initial) value in these situations.

**Comment by hamlim** [comment]
Ah yea thats a good point.

I can close this issue then, thanks!
